services:
  mysql:
    image: mysql:8.0
    container_name: plazoleta-mysql
    environment:
      MYSQL_DATABASE: plazoletadb
      MYSQL_USER: plazoleta_user
      MYSQL_PASSWORD: plazoleta_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - plazoleta_data:/var/lib/mysql
volumes:
  plazoleta_data:
